---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: jupyter-notebook
  name: jupyter-notebook
  namespace: jupyter-ns
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jupyter-notebook
  template:
    metadata:
      labels:
        k8s-app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: jitsejan/jupyter-for-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 5006
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - mountPath : /home/jovyan/work
          name: jupyter-data
      imagePullSecrets:
      - name: dockerkey
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyter-pvc
