version: '3.2'

services:
  anaconda:
    image: jitsejan/pyspark-notebook
    restart: always
    expose:
      - 8888
    volumes:
      - /home/jitsejan/notebooks:/home/jovyan/work/
    environment:
      VIRTUAL_HOST: jupyter.jitsejan.com
      LETSENCRYPT_HOST: jupyter.jitsejan.com
      LETSENCRYPT_EMAIL: mail@jitsejan.com
      GRANT_SUDO: 'yes'
    container_name: pyspark-notebook

networks:
  default:
    external:
      name: nginx-proxy

