kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-pvc
  namespace: jupyter-ns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
