kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyter-pv
  namespace: jupyter-ns
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.93.50.74
    path: "/var/nfs/notebooks"
